### ISSUE TITLE
Missing value for Radio component

### ISSUE THREAD

**Issue by LuckyLuky** [rewindui/rewindui#107]
Hi! When using `Radio` component (together with `RadioGroup`), I can't seem to get the selected value. Or to be more precise, I always get "on" as a value. 

I've checked the HTML code and also the component code and it seems like `value` attribute isn't set on the input element. If I test the same scenario with native `<input type="radio" />` element, it works correctly. 

I'd like to help and send a PR with the fix, but I first wanted to check if I'm not doing something wrong 🙂

**Comment by NickDunas** [comment]
Hello @LuckyLuky! Thank you for using Rewind-UI!

Looks like you found a bug, so I really had to fix it asap! :)

Could you please install the latest version and try again?

**Comment by NickDunas** [comment]
@LuckyLuky did you have a chance to test this out?

**Comment by MangukiyaParth** [comment]
How Can I change value programmatically?

**Comment by MangukiyaParth** [comment]
How can I update value of `RadioGroup` programmatically?
