### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by mweel1** [rewindui/rewindui#39]
How do you imagine dark mode integrating with this framework?

**Comment by NickDunas** [comment]
As a component library I want to just add the dark mode classes. Then it's up to each user which strategy they want to follow on their project.

For the documentation I plan to go with supporting system preference and manual selection to showcase the dark mode styles.

**Comment by NickDunas** [comment]
Issue closed. Feel free to follow up on this on the Discussions section if needed!
