### ISSUE TITLE
Color gradient doesn't work with 'color' property

### ISSUE THREAD

**Issue by JoDarma-lp** [rewindui/rewindui#53]
Hello, I try to use gradient color with the color property of component provide by Rewind.ui so it doesn't works as expected.

If I pass : `color="blue"` it works, the blue color I defined in tailwind.config.ts is considered

If I pass : `color="blue-500"` it doesn't works, the blue color gradient I defined in tailwind.config.ts is not considered.

How can I work with color gradient other than `className="bg-blue-500"` tailwind class ?

**Comment by NickDunas** [comment]
Hello Jo,

Could you post your code as well please?

**Comment by JoDarma-lp** [comment]
Tailwind usage : 
```
<Button type="submit" className={`bg-blue-500`}>
     S' inscrire
 </Button>
```
![Capture d’écran 2023-06-22 à 14 05 36](https://github.com/rewindui/rewindui/assets/105506527/eb7f24bc-0162-498c-94be-872e8852ebd9)

It work great ! 

With rewind color property :
```
<Button type="submit" color="blue-500">
     S' inscrire
 </Button>
```
![Capture d’écran 2023-06-22 à 14 06 53](https://github.com/rewindui/rewindui/assets/105506527/770f9771-73a9-4e5d-9e46-5723bb7b4ab0)

Not work !

Simple color property : 
```
<Button type="submit" color="blue">
     S' inscrire
 </Button>
```
![Capture d’écran 2023-06-22 à 14 12 28](https://github.com/rewindui/rewindui/assets/105506527/35609449-299b-42d5-acca-e85754bb6494)

work great !

**Comment by NickDunas** [comment]
Looks like you are trying to pass an invalid color value. 

The available color values are: white, blue, red, green, yellow, purple, gray, dark and black.

You can read about it on the docs at the Tones & Color section here: https://rewind-ui.dev/components/button

Not sure why you are trying to pass the blue-500 value though and not just use the color="blue" value!

**Comment by JoDarma-lp** [comment]
Yep, in tailwind you can defined gradient of your color and sometimes you want to use the gradient of the principal color for colorise your UI.
![Capture d’écran 2023-06-22 à 14 19 07](https://github.com/rewindui/rewindui/assets/105506527/06aa83c5-bfbc-48c1-9506-b882b40e510a)

So I can use `bg-blue-500 bg-blue-800` for different gradient of my custom blue

It's a frequent use case, so rewind ui should consider it for further customization

**Comment by NickDunas** [comment]
Please take a look at this file: https://github.com/rewindui/rewindui/blob/main/packages/core/src/theme/styles/Button.styles.ts

This is the cva file of the Button component. If you scroll down a bit you will notice that for the combination of color blue and tone solid I am indeed using bg-blue-500. 

All style files on Rewind-UI are using the cva library, which you can check out here: https://cva.style/docs/getting-started/variants

Now you can use the ThemeProvider and completely adjust the styles of any component. You can read more about it here: https://rewind-ui.dev/theming

It is really easy, give it a try and let me know what you think and if you managed to adjust it the way you want! 😃
