### ISSUE TITLE
Tabs.Tab `ref` does not allow clicking / selection

### ISSUE THREAD

**Issue by ianmacartney** [rewindui/rewindui#55]
My goal is to programmatically select a tab.

When using `useRef` with `Tabs.Tab`, doing `ref.current.click()` doesn't work. 
e.g. `<Tabs.Tab ref={ref} anchor="compare">`
The ref never seems to get populated correctly.

As a workaround, if I assign an `id`:
`<Tabs.Tab id="compare" anchor="compare">`
Then I can do `document.getElementById("compare")?.click();`

Is `ref` not being set correctly internally?

**Comment by NickDunas** [comment]
I identified the issue and will try to push a fix as soon as possible. I will let you know once I do.

**Comment by ianmacartney** [comment]
Thank you for the fast response, Nick!

**Comment by ianmacartney** [comment]
Just verified - the fix worked. Thanks again!
