### ISSUE TITLE
ImageEditor Component

### ISSUE THREAD

**Issue by detronetdip** [rewindui/rewindui#64]
As someone new to component libraries, I am interested in contributing to the project by adding a basic ImageEditor component if it's feasible and allowed, I am eager to contribute to the library by implementing it and I believe this addition would enhance the functionality of the library.

**Comment by NickDunas** [comment]
Hello @detronetdip!

Thank you for considering contributing to Rewind-UI.

Could you show me an example of an Image editor component?

**Comment by detronetdip** [comment]
@NickDunas Sure, below is the video how the final outcome will look like though we can customize and modify certain things.

https://github.com/rewindui/rewindui/assets/64276906/771a54b9-5a9c-4f08-ae9f-9773cb352f94

**Comment by NickDunas** [comment]
@detronetdip this looks really nice, but I think it is out of the scope of a ui component library. 

I would suggest you to just try to publish a separate library just for this component :)
