### ISSUE TITLE
Running rewindui storybook in local throws error with node v17 or greater.

### ISSUE THREAD

**Issue by riyajahamedi** [rewindui/rewindui#66]
**Issue Description:**
When running the **rewindui storybook** locally, an error is encountered when using Node.js version 17 or greater. The command line displays the following error message: **Error: error:0308010C:digital envelope routines::unsupported**.

**Solution:**
To resolve this issue, follow the steps below based on your operating system:

**For Windows:**

1. Open the command prompt (cmd).
2. Run the following command:

`set NODE_OPTIONS=--openssl-legacy-provider`

**For Unix, Linux, and macOS:**

1. Open the terminal.
2. Run the following command:

`export NODE_OPTIONS=--openssl-legacy-provider`

After setting the NODE_OPTIONS environment variable, navigate to the storybook folder and run the following command:

`pnpm dev`

This should start the rewindui storybook without encountering the "unsupported" error when using Node.js version 17 or higher.

Please note that these steps are specific to resolving the mentioned error related to the rewindui storybook. If you encounter any other issues or errors, please provide additional details for further assistance.

**Contributor Agreement:**
I confirm that I have read and agree to the project's contributor guidelines or licensing terms.

**Comment by NickDunas** [comment]
Hello @riyajahamedi 

Thank you for bringing this up!

Right now rewind-ui is using storybook 6.5.

I am about to upgrade to version 7 soon, but I keep postponing this as it has introduced many breaking changes and it will take some time to do so.

As a workaround to your issue if you don't want to use node v16 you can use [nvm](https://github.com/nvm-sh/nvm) to handle multiple node versions.

I will let you know once I upgrade to latest storybook.

**Comment by NickDunas** [comment]
@riyajahamedi I have just pushed an update, upgrading to storybook 7, which supports node v18.

Could you give it a test and let me know if everything works fine now for you?

**Comment by riyajahamedi** [comment]
@NickDunas Everything works fine after upgrading to storybook 7 👍
