### ISSUE TITLE
Feature Request: Add Button Story Template for Icons and Labels

### ISSUE THREAD

**Issue by singhlify** [rewindui/rewindui#75]
**Summary:**
As part of enhancing the usability and versatility of our Button component library, I propose the addition of a new story template that demonstrates buttons with icons and accompanying labels. This feature will provide developers with a clear and practical example of designing buttons for actions that require both visual cues and descriptive text.

**Feature Request:**
I suggest the creation of a new story template named `LabelWithIconTemplate`. This template should showcase buttons that include icons and text labels, demonstrating how these two elements can work together to provide a more user-friendly and informative UI.

**Use Case:**
Buttons with icons and labels are a common UI design pattern used to enhance user understanding of button actions. By showcasing this pattern in the Storybook stories, it aims to help developers implement buttons that are both visually appealing and contextually informative.

**Expected Behavior:**
- The `LabelWithIconTemplate` story template should include buttons that have icons and corresponding labels.
- The icon should be appropriately integrated into the button, and the label should provide clear and meaningful text that describes the action.
- The buttons should be customizable with different colors, tones, and sizes to accommodate various design requirements.

**Benefits:**
1. Provides developers with a concrete example of how to design buttons with icons and labels.
2. Demonstrates the synergy between icons and labels in conveying button actions.
3. Enhances the value and functionality of the Button in the component library.
4. Empowers users to create more user-friendly and accessible UI components.

**Implementation:**
The proposed story template should be structured similar to the existing Button component story templates. It should dynamically generate buttons with icons and labels based on selected color, tone, and size options.

**Impact:**
The addition of the `LabelWithIconTemplate` story template will enhance our Button component library by showcasing a widely used UI design pattern. This feature aligns with the commitment to providing developers with comprehensive and user-centric UI component solutions.

**Related Issues:**
None

**Comment by NickDunas** [comment]
Thank you for your contribution @singhlify 

I am currently on annual leave, so I will review it and get back to you once I return! 🙂
