### ISSUE TITLE
Missing input type

### ISSUE THREAD

**Issue by astraldev** [rewindui/rewindui#84]
The form input class does not have and option for phone numbers. I would use text but users would be able to input letters except i define a set of regex. A tel input type would remove that complexity and make the code look neat.

Something like this: 
```
<Input type="tel" />
```

Please consider adding it.

**Comment by NickDunas** [comment]
You are right @astraldev!

I will add it at some point on Monday. I will let you know here once I do.

Thank you for pointing this out.

**Comment by NickDunas** [comment]
@astraldev an update has just been pushed. Please try installing latest version.

**Comment by astraldev** [comment]
Thank you very much
