### ISSUE TITLE
Center Alignment of Table Headers and Footer

### ISSUE THREAD

**Issue by singhlify** [rewindui/rewindui#90]
### Problem
In the current state of the project's Storybook example, the alignment of table headers and footers was inconsistent with the alignment of the table body cells. Specifically, all the header and footer texts were center-aligned, while in the body, only the first column was center-aligned, and the rest were left-aligned. This inconsistency led to an unpolished and visually unappealing table layout.

### Solution
I propose adjusting the alignment of table headers and footers to ensure a more consistent and polished appearance. The changes made are as follows:
- Center-align the first column headers and footers.
- Left-align the remaining headers and footers.
  
These adjustments result in a more visually appealing and uniform table layout within the Storybook example.

**Steps to Reproduce:**
1. Navigate to the [Storybook example](https://storybook.rewind-ui.dev/?path=/docs/components-table--docs).
2. Observe the alignment of table headers and footers.
3. Observe the alignment of table body cells.

**Expected Behavior:**
- Headers and footers should exhibit consistent alignment with the body cells for a polished appearance.

**Screenshots:**
![image](https://github.com/rewindui/rewindui/assets/40722529/eb04ced7-a784-4293-8a59-b618389a9f03)

**Comment by NickDunas** [comment]
Thank you for your PR @singhlify!

**Comment by singhlify** [comment]
Hi @NickDunas ,
Sorry for troubling you 🙏 but if possible can you please add `hacktoberfest-accepted` tag on this PR? I am a participant in Hacktoberfest so, it will help.

![image](https://github.com/rewindui/rewindui/assets/40722529/e0ea5900-cdb3-4e67-bb2d-29a3b2d9715c)

**Comment by NickDunas** [comment]
I just did @singhlify
